-- ============================================================================
-- model_deployments table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.model_deployments (
    -- Unique internal identifier for the model version record.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Logical model name (for example, FraudDetectionModel).
    model_name TEXT NOT NULL,

    -- Human-readable model version (for example, v1, v1.2.0).
    version TEXT NOT NULL,

    -- Unique MLflow run identifier for traceability.
    mlflow_run_id TEXT NOT NULL,

    -- Timestamp when this model version was registered.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Flag that indicates if this version is currently active in production.
    is_active BOOLEAN NOT NULL DEFAULT FALSE,

    -- F1 score measured from confirmed production outcomes.
    f1_score DOUBLE PRECISION,

    -- Precision measured from confirmed production outcomes.
    precision DOUBLE PRECISION,

    -- Recall measured from confirmed production outcomes.
    recall DOUBLE PRECISION,

    -- AUC-ROC score associated with this model version.
    auc_roc DOUBLE PRECISION,

    -- Start timestamp of the training data window used for this model.
    training_data_from TIMESTAMPTZ NOT NULL,

    -- End timestamp of the training data window used for this model.
    training_data_to TIMESTAMPTZ NOT NULL,

    CONSTRAINT model_deployments_mlflow_run_id_uk UNIQUE (mlflow_run_id),
    CONSTRAINT model_deployments_training_range_ck
        CHECK (training_data_from <= training_data_to),
    CONSTRAINT model_deployments_f1_score_ck
        CHECK (f1_score IS NULL OR (f1_score >= 0 AND f1_score <= 1)),
    CONSTRAINT model_deployments_precision_ck
        CHECK (precision IS NULL OR (precision >= 0 AND precision <= 1)),
    CONSTRAINT model_deployments_recall_ck
        CHECK (recall IS NULL OR (recall >= 0 AND recall <= 1)),
    CONSTRAINT model_deployments_auc_roc_ck
        CHECK (auc_roc IS NULL OR (auc_roc >= 0 AND auc_roc <= 1))
);

CREATE INDEX IF NOT EXISTS idx_model_deployments_active
    ON public.model_deployments (created_at DESC)
    WHERE is_active IS TRUE;

-- ============================================================================
-- predictions_history table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.predictions_history (
    -- Unique internal identifier of the prediction event.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Transaction identifier to correlate with transactional sources.
    transaction_id UUID NOT NULL,

    -- Model version identifier used to generate this prediction.
    model_version_id BIGINT NOT NULL,

    -- Raw fraud probability score returned by the model.
    prediction_score DOUBLE PRECISION NOT NULL,

    -- Predicted fraud label (TRUE means predicted fraud).
    prediction_label BOOLEAN NOT NULL,

    -- Ground-truth label, populated later when available.
    actual_label BOOLEAN,

    -- Inference timestamp for this prediction event.
    "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- End-to-end inference latency in milliseconds.
    latency_ms DOUBLE PRECISION NOT NULL,

    CONSTRAINT predictions_history_model_version_fk
        FOREIGN KEY (model_version_id)
        REFERENCES public.model_deployments (id),
    CONSTRAINT predictions_history_prediction_score_ck
        CHECK (prediction_score >= 0 AND prediction_score <= 1),
    CONSTRAINT predictions_history_latency_ms_ck
        CHECK (latency_ms >= 0)
);

CREATE INDEX IF NOT EXISTS idx_predictions_history_model_version_id
    ON public.predictions_history (model_version_id);

CREATE INDEX IF NOT EXISTS idx_predictions_history_timestamp
    ON public.predictions_history ("timestamp");

CREATE INDEX IF NOT EXISTS idx_predictions_history_transaction_id
    ON public.predictions_history (transaction_id);

-- ============================================================================
-- drift_reports table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.drift_reports (
    -- Unique internal identifier for each drift report.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Timestamp when the drift analysis report was generated.
    report_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Model version evaluated by this drift report.
    model_version_id BIGINT NOT NULL,

    -- Global drift score produced by the drift analysis.
    drift_score DOUBLE PRECISION NOT NULL,

    -- Per-feature drift details stored as flexible JSONB.
    feature_drifts JSONB NOT NULL,

    -- Indicates whether the report triggered an operational alert.
    alert_triggered BOOLEAN NOT NULL DEFAULT FALSE,

    -- Optional remediation action taken after this report.
    remediation_action TEXT,

    CONSTRAINT drift_reports_model_version_fk
        FOREIGN KEY (model_version_id)
        REFERENCES public.model_deployments (id),
    CONSTRAINT drift_reports_drift_score_ck
        CHECK (drift_score >= 0 AND drift_score <= 1)
);

CREATE INDEX IF NOT EXISTS idx_drift_reports_report_date
    ON public.drift_reports (report_date);

CREATE INDEX IF NOT EXISTS idx_drift_reports_model_version_id
    ON public.drift_reports (model_version_id);

CREATE INDEX IF NOT EXISTS idx_drift_reports_alerts_true
    ON public.drift_reports (report_date DESC)
    WHERE alert_triggered IS TRUE;

-- ============================================================================
-- alert_log table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.alert_log (
    -- Unique internal identifier for the alert event.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Alert category/type (for example, HIGH_FRAUD_RATE or DRIFT_DETECTED).
    alert_type TEXT NOT NULL,

    -- Operational severity level of the alert.
    severity TEXT NOT NULL,

    -- Human-readable alert message for operators.
    message TEXT NOT NULL,

    -- Timestamp when the alert was triggered.
    triggered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Timestamp when the alert was acknowledged.
    acknowledged_at TIMESTAMPTZ,

    -- User or operator that acknowledged the alert.
    acknowledged_by TEXT,

    CONSTRAINT alert_log_severity_ck
        CHECK (severity IN ('INFO', 'WARNING', 'HIGH', 'CRITICAL'))
);

CREATE INDEX IF NOT EXISTS idx_alert_log_triggered_at
    ON public.alert_log (triggered_at DESC);

CREATE INDEX IF NOT EXISTS idx_alert_log_open_unack
    ON public.alert_log (triggered_at DESC)
    WHERE acknowledged_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_alert_log_severity
    ON public.alert_log (severity);
