apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: ${GF_TIMESCALEDB_USER}
    database: ${GF_TIMESCALEDB_DB}
    secureJsonData:
      password: ${GF_TIMESCALEDB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    editable: true

  - name: PostgreSQL
    uid: postgresql
    type: postgres
    access: proxy
    url: postgresql:5432
    user: ${GF_POSTGRES_USER}
    database: ${GF_POSTGRES_DB}
    secureJsonData:
      password: ${GF_POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: "2.51.0"
    editable: true
